/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Identidade de marca (FASE 1)
        ml: { yellow: '#FFE600', blue: '#3483FA', 'blue-hover': '#2968C8', green: '#00A650' },
        ink: { primary: 'rgba(0, 0, 0, 0.9)', secondary: 'rgba(0, 0, 0, 0.55)' },
        page: '#EBEBEB',
        line: 'rgba(0, 0, 0, 0.1)',
        // Tokens semânticos (FASE 2) — única fonte de verdade de cor; nada de hex nos componentes
        background: '#EBEBEB',
        surface: '#FFFFFF',
        foreground: 'rgba(0, 0, 0, 0.9)',
        'muted-foreground': 'rgba(0, 0, 0, 0.55)',
        border: 'rgba(0, 0, 0, 0.1)',
        primary: { DEFAULT: '#3483FA', hover: '#2968C8', foreground: '#FFFFFF' },
        secondary: { DEFAULT: '#FFE600', hover: '#F2DC00', foreground: 'rgba(0, 0, 0, 0.9)' },
        success: { DEFAULT: '#00A650', hover: '#00914A', soft: '#E6F5EC', foreground: '#FFFFFF', 'soft-foreground': '#0A6B37' },
        warning: { DEFAULT: '#B45309', soft: '#FEF3C7', foreground: '#FFFFFF', 'soft-foreground': '#8A4208' },
        destructive: { DEFAULT: '#DC2626', hover: '#B91C1C', soft: '#FEE2E2', foreground: '#FFFFFF', 'soft-foreground': '#991B1B' },
        info: { DEFAULT: '#2968C8', soft: '#E3EDFF', foreground: '#FFFFFF', 'soft-foreground': '#1D4F9E' },
        // Tema "ingressos" (auditoria buyticketbrasil, docs/DESIGN_AUDIT.md) — namespaces próprios
        ticket: {
          primary: '#5C4BF9',
          'primary-press': '#4A3BD6',
          'primary-deep': '#241542',
          'primary-soft': '#EEECFE',
          'primary-tint': '#5C4BF90A',
          'primary-outline': '#5C4BF980',
          'on-primary': '#FFFFFF',
          accent: '#0FA968',
          'accent-soft': '#E2F6EE',
          success: '#0B7F4F',
          caution: '#FFB100',
          'caution-soft': '#FFF9EE',
          'caution-text': '#4D370F',
          warn: '#C2410C',
          'warn-soft': '#FBEADF',
          danger: '#DC2626',
          'danger-soft': '#FBE5E5',
          text: '#14151A',
          muted: '#6B7280',
          faint: '#9AA0AA',
          outline: '#C9CDD3',
          border: '#E4E6EB',
          hairline: '#EFF1F4',
          surface: '#FFFFFF',
          'surface-muted': '#F1F2F4',
          'surface2': '#EDEFF2',
          scrim: '#14151A80',
          'scrim-strong': '#14151ABF',
          glass: '#00000038',
          'glass-strong': '#0006',
          pix: '#32BCAD',
          'pix-soft': '#DDF1EF',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        // Tema ingressos: Hanken Grotesk (corpo), Lexend (títulos), Sora (numérico)
        hanken: ['"Hanken Grotesk"', 'sans-serif'],
        lexend: ['Lexend', 'sans-serif'],
        sora: ['Sora', 'sans-serif'],
      },
      fontSize: {
        display: ['2.5rem', { lineHeight: '1.15', fontWeight: '700', letterSpacing: '-0.02em' }],
        h1: ['2rem', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.01em' }],
        h2: ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['1.25rem', { lineHeight: '1.35', fontWeight: '600' }],
        h4: ['1.125rem', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['1rem', { lineHeight: '1.5' }],
        'body-small': ['0.875rem', { lineHeight: '1.45' }],
        caption: ['0.75rem', { lineHeight: '1.4' }],
        label: ['0.875rem', { lineHeight: '1.2', fontWeight: '500' }],
        // Escala do tema ingressos (auditada: size/line-height/weight/letter-spacing)
        't-display': ['28px', { lineHeight: '34px', fontWeight: '700', letterSpacing: '-0.42px' }],
        't-h1': ['24px', { lineHeight: '30px', fontWeight: '700', letterSpacing: '-1.5px' }],
        't-h2': ['20px', { lineHeight: '26px', fontWeight: '600', letterSpacing: '-1px' }],
        't-title': ['18px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '-0.5px' }],
        't-price-l': ['30px', { lineHeight: '36px', fontWeight: '600', letterSpacing: '-0.3px' }],
        't-amount': ['46px', { lineHeight: '52px', fontWeight: '700', letterSpacing: '-1px' }],
        't-total': ['20px', { lineHeight: '24px', fontWeight: '700', letterSpacing: '-0.1px' }],
        't-price-m': ['16px', { lineHeight: '20px', fontWeight: '700', letterSpacing: '-0.5px' }],
        't-body': ['16px', { lineHeight: '22px', fontWeight: '400' }],
        't-body-strong': ['16px', { lineHeight: '22px', fontWeight: '600', letterSpacing: '-0.32px' }],
        't-body-s': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        't-label': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        't-label-strong': ['14px', { lineHeight: '18px', fontWeight: '700' }],
        't-caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        't-caption-strong': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        't-eyebrow': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.96px' }],
        't-micro': ['11px', { lineHeight: '14px', fontWeight: '600', letterSpacing: '-0.44px' }],
        't-legal': ['11px', { lineHeight: '16px', fontWeight: '500' }],
        't-nano': ['10px', { lineHeight: '13px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '6px',
        xl: '14px',
        // Tema ingressos (auditados)
        't-bar': '2px',
        't-control': '10px',
        't-tile': '12px',
        't-card': '16px',
        't-sheet': '22px',
        't-circle': '15px',
        't-pill': '999px',
      },
      boxShadow: {
        card: '0 1px 2px 0 rgba(0, 0, 0, 0.15)',
        'card-hover': '0 6px 16px 0 rgba(0, 0, 0, 0.12)',
        elevated: '0 12px 32px 0 rgba(0, 0, 0, 0.14)',
        // Tema ingressos (auditados)
        't-card': '0 1px 6px -3px #00000040',
        't-row': '0 2px 8px #0000000F',
        't-panel': '0 3px 10px 0 #14141F0F',
        't-hover': '0 12px 28px #14151A24',
        't-dialog': '0 18px 40px #14151A24',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
      },
      animation: {
        'fade-in': 'fade-in 200ms ease-out',
        'slide-in-right': 'slide-in-right 200ms ease-out',
      },
    },
  },
  plugins: [],
}
